CREATE TABLE tree_name (
	id	INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name	VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tree (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_tree INT UNSIGNED NOT NULL,
	id_node INT UNSIGNED NOT NULL,
	id_parent INT UNSIGNED,
	
	INDEX idx_tree (id_tree),
	UNIQUE INDEX idx_tree_node (id_tree, id_node),
	FOREIGN KEY(id_tree) REFERENCES tree_name(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE active_tree (
	id_user INT UNSIGNED NOT NULL PRIMARY KEY,
	id_tree INT UNSIGNED NOT NULL UNIQUE
);

